
package example.com.spring.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerWebServiceService", targetNamespace = "http://com.example/spring/soap", wsdlLocation = "http://localhost:8081/ws/customer?wsdl")
public class CustomerWebServiceService
    extends Service
{

    private final static URL CUSTOMERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERWEBSERVICESERVICE_EXCEPTION;
    private final static QName CUSTOMERWEBSERVICESERVICE_QNAME = new QName("http://com.example/spring/soap", "CustomerWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/customer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERWEBSERVICESERVICE_WSDL_LOCATION = url;
        CUSTOMERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public CustomerWebServiceService() {
        super(__getWsdlLocation(), CUSTOMERWEBSERVICESERVICE_QNAME);
    }

    public CustomerWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERWEBSERVICESERVICE_QNAME, features);
    }

    public CustomerWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERWEBSERVICESERVICE_QNAME);
    }

    public CustomerWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERWEBSERVICESERVICE_QNAME, features);
    }

    public CustomerWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerWebService
     */
    @WebEndpoint(name = "CustomerWebServicePort")
    public CustomerWebService getCustomerWebServicePort() {
        return super.getPort(new QName("http://com.example/spring/soap", "CustomerWebServicePort"), CustomerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerWebService
     */
    @WebEndpoint(name = "CustomerWebServicePort")
    public CustomerWebService getCustomerWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.example/spring/soap", "CustomerWebServicePort"), CustomerWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw CUSTOMERWEBSERVICESERVICE_EXCEPTION;
        }
        return CUSTOMERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
